# Generated by Django 2.1.5 on 2020-06-23 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200622_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_no', models.CharField(max_length=100)),
                ('tender_title', models.CharField(max_length=200)),
                ('tender_description', models.TextField()),
                ('tender_updated', models.DateTimeField(default=datetime.datetime(2020, 6, 23, 13, 43, 37, 708634), verbose_name='Tender Updated')),
                ('tender_start_date', models.DateTimeField()),
                ('tender_end_date', models.DateTimeField()),
                ('tender_company', models.CharField(choices=[('HM', 'Harsh Marketing'), ('JE', 'Jai Enterprises')], default='JE', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 13, 43, 37, 708634), verbose_name='Item updated'),
        ),
    ]
