# Generated by Django 2.1.5 on 2020-06-23 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200623_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 15, 18, 54, 163453), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 15, 18, 54, 164455), verbose_name='Tender Updated'),
        ),
    ]
