# Generated by Django 2.1.5 on 2020-06-23 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200623_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 16, 3, 53, 513074), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 16, 3, 53, 513074), verbose_name='Tender Updated'),
        ),
    ]
