# Generated by Django 2.1.5 on 2020-06-30 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200623_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='tender_company',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='tender_description',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='tender_end_date',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='tender_materials',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 16, 38, 9, 964797), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 16, 38, 9, 964797), verbose_name='Tender Updated'),
        ),
    ]
