# Generated by Django 2.1.5 on 2020-06-30 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200630_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_no',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 18, 10, 58, 988152), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 18, 10, 58, 989152), verbose_name='Tender Updated'),
        ),
    ]
