# Generated by Django 2.1.5 on 2020-06-30 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200630_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='tender',
            name='tender_status',
            field=models.CharField(choices=[('OG', 'On going'), ('CM', 'Completed')], default='OG', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_no',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 19, 3, 19, 326652), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 19, 3, 19, 327651), verbose_name='Tender Updated'),
        ),
    ]
