# Generated by Django 2.1.5 on 2020-07-01 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200701_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.CharField(max_length=100)),
                ('qty_cus', models.CharField(max_length=100)),
                ('qty_con', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TenderEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_no', models.CharField(max_length=100, verbose_name='Estimate Number')),
                ('est_desc', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='est_desc',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='tender_no',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='est_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TenderEstimate', verbose_name='Estimate Number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 55, 1, 177801), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 55, 1, 178803), verbose_name='Tender Updated'),
        ),
        migrations.AddField(
            model_name='tenderestimate',
            name='tender_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tender'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item'),
        ),
    ]
