# Generated by Django 2.1.5 on 2020-07-01 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200701_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='tender_title',
            new_name='tender_order',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 58, 26, 929661), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 21, 58, 26, 930661), verbose_name='Tender Updated'),
        ),
    ]
