# Generated by Django 2.1.5 on 2020-07-01 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200701_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='est_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 5, 14, 798323), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 5, 14, 799321), verbose_name='Tender Updated'),
        ),
    ]
