# Generated by Django 2.1.5 on 2020-07-01 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200701_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='est_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Estimate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 12, 4, 764497), verbose_name='Item updated'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 12, 4, 765496), verbose_name='Tender Updated'),
        ),
    ]
